name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install Yarn
        run: corepack enable |
          corepack prepare yarn@3.3.1 --activate
      # Yarn dependencies cannot be cached until yarn is installed
      # WORKAROUND: https://github.com/actions/setup-node/issues/531
      - name: Extract cached dependencies
        uses: actions/setup-node@v3
        with:
          cache: yarn
      - name: Update dependencies
        run: corepack yarn --immutable
      - name: Lint
        run: yarn run lint
      - name: Format
        if: always()
        run: yarn run checkFormat
      - name: Build
        if: always()
        run: yarn run build
